import os
import hou
from utils import deadline_utils
from utils import file_utils
import tempfile
import subprocess
from typing import Any


class SimSubmitter:

    def __init__(self, kwargs):
        self.node = kwargs["node"]
        self.name = self.node.parm("name").eval()
        self.comment = self.node.parm("comment").eval()
        self.nodes_to_save = self.node.parm("nodes_to_save")

    def get_cache_nodes_as_list(self):
        return [i.evalAsNodePath() for i in self.nodes_to_save.multiParmInstances()]


    def cache_me_string(self):

        caches = f"nodes_to_cache = {str(self.get_cache_nodes_as_list())}"
        log = '''
import logging
# this file is automatically generated - DO NOT EDIT
level = logging.DEBUG
fmt = '[%(levelname)s] %(asctime)s - %(message)s'
logging.basicConfig(level=level, format = fmt)
for node in nodes_to_cache:
    parm_to_process = hou.parm(f'{node}/execute')
    if parm_to_process is not None:
        logging.info(f'{node} - Starting')
        parm_to_process.pressButton()
        logging.info(f'{node} - Completed')
    else:
        logging.error(f'MISSING NODE: {node} - Node does not exist at this path')
        continue
        '''

        return f"{caches}{log}"
    
    
    def cache_me_file(self):
        cache = hou.hipFile.path().replace(".hipnc", "_cacheMe.py")
        with open(cache, "w") as f:
            f.write(self.cache_me_string())
        return cache
    

    def runSafetyChecks(self):
        
        if self.name.replace(" ", "") == "":
            self.name = "Sim_Submission"

        if self.nodes_to_save.eval() == 0:
            hou.ui.displayMessage("No nodes selected to save")
            return False
        
        for i in self.nodes_to_save.multiParmInstances():
            if i.evalAsString() == "":
                hou.ui.displayMessage("Please select nodes in every multi parm instance.")
                return False

        return True
    

    def save_popup(self):
        """
        Save option for sim submitter.
        """
        text = "File needs to save before render can be submitted.\nIncrement file?"
        buttons = ["Save Current", "Increment file", "Cancel"]
        confirm = hou.ui.displayMessage(text, buttons, default_choice=2, close_choice=2)

        match confirm:
            case 0:
                hou.hipFile.save()
                return True
            case 1:
                hou.hipFile.saveAndIncrementFileName()
                return True
            case 2:
                return False



    def submit_to_deadline(self):
        """
        Creates and submits job to deadline.
        """
        if self.runSafetyChecks():
            if self.save_popup():

                hou.hipFile.save()
                job_info = tempfile.NamedTemporaryFile(delete=False, suffix="_job.info", mode="w", encoding="utf-8")
                plugin_info = tempfile.NamedTemporaryFile(delete=False, suffix="_plugin.info", mode="w", encoding="utf-8")
                
                proj = os.getenv("PROJ")
                database = os.getenv("DATABASE")
                pypath = deadline_utils.get_pypath()
                
                infile = file_utils.reformat_path(hou.hipFile.path())
                ocio = os.environ["OCIO"]
                
                job_info.write(
                fr"""Plugin=UHFarmCache
                Name=BushtailBandit_{self.name}
                Comment={self.comment}

                EnvironmentKeyValue0=PROJ={proj}
                EnvironmentKeyValue1=DATABASE={database}

                EnvironmentKeyValue2=PIPELINE_PYTHONPATH={pypath}
                EnvironmentKeyValue3=HOUDINI_PYTHONPATH={pypath};%HOUDINI_PYTHONPATH%
                EnvironmentKeyValue4=PYTHONPATH={pypath};%PYTHONPATH%
                EnvironmentKeyValue5=OCIO={ocio}
                """
                )

                job_info.close()

                plugin_info.write(
                fr"""SceneFile={infile}
                cacheMeFile={self.cache_me_file()}
                """
                )
                plugin_info.close()

                cmd = deadline_utils.get_deadline()

                # Submit job
                subprocess.run([
                    cmd,
                    job_info.name,
                    plugin_info.name
                ])
                hou.ui.displayMessage("Sim Job Submitted!")  

